baseURL = "grupowicze.pl"
languageCode = "en-us"
title = "Grupowicze | Comming Soon Social Media App by Ralf-IT.pl"
theme = "infinity"
removePathAccents = true

[params]
# HTML before the closing </head>
customHead = ""

# Navigation
[params.navigation]
logo = "Grupowicze.pl"
home = "Home"
about = "About"
service = "Services"
contact = "Contact"

# Hero Area
[params.hero]
enable            = true
bg                = "images/header-bg.jpg"
title             = "Grupowicze"
subtitle          = "Coming soon. Made by Ralf-IT from Poland."
btnText           = "Get Started"

# counter
disableCountdown  = false
countdownYear = "2020"
countdownMonth = "08"
countdownDay  = "31"

# About Section
[params.about]
enable      = true
heading     = "[1]"
description = "[1.1]"

[[params.about.sliderItem]]
image   = "images/about/1.jpg"
[[params.about.sliderItem]]
image   = "images/about/2.jpg"
[[params.about.sliderItem]]
image   = "images/about/3.jpg"
[[params.about.sliderItem]]
image   = "images/about/2.jpg"


# Service Section
[params.service]
enable      = true
title       = "[3]"
subtitle    = "[3.1]"
[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-strategy"
title   = "[4]"
description = "[4.1]"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "[5]"
description = "[5.1]"
delay   = "0.2s"

# ... <can put as many as needed>

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "[11]"
description = "[11.1]"
delay   = "1.5s"


# Call to Action Section
[params.cta]
enable      = true
bg          = "images/call-to-action.jpg"
title       = "Subscribe to our mailing list"
subtitle    = "[12]"

[params.contact]
enable      = true
title       = "Get In Touch"
subtitle    = "[13]"
